"use client";
import { useState } from "react";
import "../globals.css";
import Sidebar from "./components/sidebar";
import { Montserrat } from "next/font/google";
const inter = Montserrat({ subsets: ["latin"] });
import { usePathname } from "next/navigation";
import { useAmp } from "next/amp";
// export const metadata = {
//   title: "admin",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        {" "}
        {pathName === "/login" ? <div></div> : <Sidebar />}
        <main
          className={`${pathName === "/login" ? "" : "md:ml-60 mb-10"}  w-full`}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
