import "../globals.css";
import Sidebar from "./components/sidebar";
import { Montserrat } from "next/font/google";
const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "admin",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        {" "}
        <Sidebar />
        <main className="md:ml-60 mb-10 w-full">
          {children}
          {/* <div className="flex justify-center mt-10  "></div> */}
        </main>
      </body>
    </html>
  );
}
